# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Fenix Productions
email: support@bluefenix.net
description: professional geek ramblings <br> est. 2003
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chris.pelatari.com" # the base hostname & protocol for your site
twitter_username: bluefenix_net
github_username:  ChrisPelatari
mastadon_username:
https://hachyderm.io/@blue_fenix

timezone: America/Chicago

post:
  template: _layouts/post_template.md
  extension: md

page:
  template: _layouts/post_template.md
  extension: md

editor: code

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

github: [metadata]