# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Pelatari
email: chris@pelatari.com
description: > # this means to ignore newlines until "baseurl:"
  May I never be complete.
  May I never be content.
  May I never be perfect.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chris.pelatari.com" # the base hostname & protocol for your site
twitter_username: ChrisPelatari
github_username:  ChrisPelatari

post:
  template: _layouts/post.md
  extension: md

# Build settings
markdown: kramdown
